title: "Goyum Samuditha | Data Scientist & Business Analyst"
description: "Goyum Samuditha is a Data Scientist and Business Analyst specializing in machine learning, NLP, predictive analytics, BI dashboards, cloud-based AI pipelines, and data-driven business solutions. View projects, certifications, and portfolio."
author: "Goyum Samuditha"
url: "https://goyumsamuditha.github.io"
keywords: "Goyum Samuditha, Data Scientist, Business Analyst, Python, R, Power BI, Tableau, SQL, Databricks, Machine Learning Engineer, MLOps, MLFlow, Data Analytics, Portfolio"

permalink: /articles/:title/

collections:
  projects:
    output: true
    permalink: /projects/:name/
